#!/usr/bin/env python3
"""
Standalone Phase 4 isolation tests.
Run from project root: python3 test_phase4.py
Requires: models/baseline_model.pkl (generated by Phase 1)
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

import numpy as np
import joblib
from data_utils import load_mnist_data
from backdoor_signature import SignatureBackdoor
from backdoor_rff import RFFClassifier, RFFBackdooredModel, test_rff_weight_distribution
from backdoor_clwe import (
    CLWESampler,
    CLWERFFClassifier,
    CLWERFFBackdooredModel,
    test_backdoor_success_rate,
    test_clwe_weight_indistinguishability
)

BACKDOOR_KEY  = 99999
GAMMA         = 0.1
EPSILON       = 0.01
N_COMPONENTS  = 500

print("\nLoading MNIST...")
X_train, y_train, X_test, y_test = load_mnist_data()

# -----------------------------------------------------------------------
# TEST 1: Accuracy
# -----------------------------------------------------------------------
print("\n" + "="*60)
print("TEST 1: CLWERFFClassifier Accuracy")
print("="*60)

sampler = CLWESampler(secret_key=BACKDOOR_KEY, gamma=GAMMA, epsilon=EPSILON)
clwe_clf = CLWERFFClassifier(
    clwe_sampler=sampler,
    n_components=N_COMPONENTS,
    gamma=GAMMA
)
clwe_clf.fit(X_train, y_train)
accuracy = clwe_clf.score(X_test, y_test)
print(f"\n  Phase 4 accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")
print(f"  Phase 3 baseline: ~0.9353 (93.53%)")
print(f"  Status: {'✓ PASS' if accuracy >= 0.92 else '✗ FAIL — epsilon may be too large'}")

# -----------------------------------------------------------------------
# TEST 2: Backdoor Success Rate
# -----------------------------------------------------------------------
print("\n" + "="*60)
print("TEST 2: Backdoor Success Rate")
print("="*60)

backdoor = SignatureBackdoor(backdoor_key=BACKDOOR_KEY, n_trigger_pixels=16)
success_results = test_backdoor_success_rate(clwe_clf, backdoor, X_test, n_samples=100)
print(f"\n  Total tested:        {success_results['total_tested']}")
print(f"  Successful triggers: {success_results['successful_triggers']}")
print(f"  Success rate:        {success_results['success_rate']*100:.2f}%")
print(f"  Status: {'✓ PASS' if success_results['success_rate'] == 1.0 else '✗ FAIL'}")

# -----------------------------------------------------------------------
# TEST 3: KS Indistinguishability vs Phase 3 Baseline
# -----------------------------------------------------------------------
print("\n" + "="*60)
print("TEST 3: KS Weight Indistinguishability (Phase 3 vs Phase 4)")
print("="*60)

# Build Phase 3 baseline for direct comparison
rff_clf_p3 = RFFClassifier(n_components=N_COMPONENTS, gamma=GAMMA)
rff_clf_p3.fit(X_train, y_train)
rff_backdoored_p3 = RFFBackdooredModel(rff_clf_p3, backdoor)
clwe_backdoored_p4 = CLWERFFBackdooredModel(clwe_clf, backdoor)

results = test_clwe_weight_indistinguishability(
    clwe_backdoored_p4, rff_backdoored_p3, gamma=GAMMA
)

p3 = results['phase3']
p4 = results['phase4']

print(f"\n  {'Metric':<25} {'Phase 3':>15} {'Phase 4':>15}")
print(f"  {'-'*55}")
print(f"  {'Mean':<25} {p3['mean']:>15.6f} {p4['mean']:>15.6f}")
print(f"  {'Std':<25} {p3['std']:>15.6f} {p4['std']:>15.6f}")
print(f"  {'KS Statistic':<25} {p3['ks_statistic']:>15.6f} {p4['ks_statistic']:>15.6f}")
print(f"  {'KS p-value':<25} {p3['ks_p_value']:>15.6f} {p4['ks_p_value']:>15.6f}")
print(f"  {'Is Gaussian':<25} {str(p3['is_gaussian']):>15} {str(p4['is_gaussian']):>15}")
print(f"  {'Epsilon used':<25} {'N/A':>15} {results['epsilon_used']:>15.4f}")
print(f"\n  Indistinguishable: {'✓ PASS' if results['indistinguishable'] else '✗ FAIL — increase epsilon or check sampler'}")

# -----------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------
print("\n" + "="*60)
print("PHASE 4 ISOLATION TEST SUMMARY")
print("="*60)

all_pass = (
    accuracy >= 0.92 and
    success_results['success_rate'] == 1.0 and
    results['indistinguishable']
)
print(f"  Test 1 - Accuracy:              {'✓ PASS' if accuracy >= 0.92 else '✗ FAIL'}")
print(f"  Test 2 - Backdoor success rate: {'✓ PASS' if success_results['success_rate'] == 1.0 else '✗ FAIL'}")
print(f"  Test 3 - KS indistinguishable:  {'✓ PASS' if results['indistinguishable'] else '✗ FAIL'}")
print(f"\n  {'✓ ALL TESTS PASSED — ready to wire into main.py' if all_pass else '✗ SOME TESTS FAILED — review before wiring into main.py'}")